FROM redis/redis-stack:latest 

USER root
RUN apt-get update && DEBIAN_FRONTEND=“noninteractive” apt-get install -y --no-install-recommends \
       nginx \
       ca-certificates \
       apache2-utils \
       certbot \
       python3-certbot-nginx \
       sudo \
       cifs-utils \
       && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /opt/redis_stack
RUN chmod -R 777 /opt/redis_stack
WORKDIR /opt/redis_stack

RUN useradd redis
USER redis
COPY run_first.sh ./run_first.sh
COPY redis.conf /etc/redis/redis.conf
COPY nginx.conf /etc/nginx/nginx.conf

USER root
RUN chmod a+x run_first.sh

CMD ["./run_first.sh"]